<?php include __DIR__."/../_header.phtml"; ?>
<?php /** @var Domains_Base $data */ ?>

<a href="/freezer/FreezerItem">Back</a>
<?php if ($data) { ?>
    <form>
        <div class = "form-group">
            <label>Id</label>
            <input type="number" id="entry_id" class="form-control-plaintext"
                   value="<?=$data->id?>">
        </div>
        <div class = "form-group">
            <label>Name</label>
            <input type="text" id="name" class="form-control-plaintext"
                   value="<?=$data->name?>">
        </div>
        <div class = "form-group">
            <label>Entry</label>
            <input type="date" id="entry" class="form-control-plaintext"
                   value="<?=$data->entry?>">
        </div>
        <div class = "form-group">
            <label>Description</label>
            <input type="text" id="description" class="form-control-plaintext"
                   value="<?=$data->description?>">
        </div>
        <div class = "form-group">
            <label>Exp</label>
            <input type="date" id="exp" class="form-control-plaintext"
                   value="<?=$data->exp?>">
        </div>
    </form>
    <br>
    <button onclick="update_item()" class="btn btn-warning">Update</button>
    <button onclick="get_json()" class="btn btn-primary">Get Json</button>
    <br>
    <br>
    <div id="json-representation"></div>
<?php } else { ?>
    <div>No data found.</div>
<?php } ?>

<script>
    function update_item(){
        const id = document.getElementById("entry_id").value;
        const name = document.getElementById("name").value;
        const entry = document.getElementById("entry").value;
        const description = document.getElementById("description").value;
        const exp = document.getElementById("exp").value;

        fetch(window.location, {
            method: "PUT",
            body: "id=" + id + "&name=" + name + "&entry=" + entry +
                "&description=" + description + "&exp=" + exp
        }).then(response => alert("Updated!"));
    }

    function get_json() {
        const element = document.getElementById("json-representation");
        fetch(window.location, {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        }).then(response => response.json().then(
            j => element.innerHTML = JSON.stringify(j)
        ));
    }
</script>


<?php include __DIR__."/../_footer.phtml"; ?>
