GET http://localhost/freezer/FreezerItem
Accept: application/json

### Test post request
POST http://localhost/freezer/FreezerItem
Content-Type: application/x-www-form-urlencoded

name=Gulasch&description=Gutes haltbares Gulasch&entry=2023-05-23&exp=2024-05-03

###

GET http://localhost/freezer/FreezerItem/6
Accept: application/json

####

DELETE http://localhost/freezer/FreezerItem/6

###

PUT http://localhost/freezer/FreezerItem/3
Content-Type: application/x-www-form-urlencoded

name=Gulasch&description=Gutes haltbares Gulasch&entry=2023-05-23&exp=2024-05-03